// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityProject.Infrustructure.Data;

#nullable disable

namespace UniversityProject.Infrustructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240610130129_CreateInstructorModel")]
    partial class CreateInstructorModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UniversityProject.Domain.Entities.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"), 1L, 1);

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Period")
                        .HasColumnType("datetime2");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("UniversityProject.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"), 1L, 1);

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("InstructorID")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerID")
                        .HasColumnType("int");

                    b.HasKey("DepartmentID");

                    b.HasIndex("InstructorID");

                    b.HasIndex("ManagerID")
                        .IsUnique()
                        .HasFilter("[ManagerID] IS NOT NULL");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("UniversityProject.Domain.Entities.DepartmentCourse", b =>
                {
                    b.Property<int>("DepartmentID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("CourseID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("DepartmentID", "CourseID");

                    b.HasIndex("CourseID");

                    b.ToTable("DepartmentCourses");
                });

            modelBuilder.Entity("UniversityProject.Domain.Entities.Instructor", b =>
                {
                    b.Property<int>("InstructorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HeadOfDepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagingDepartmentDepartmentID")
                        .HasColumnType("int");

                    b.Property<int?>("ManagingDepartmentID")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TeachingDepartmentID")
                        .HasColumnType("int");

                    b.HasKey("InstructorID");

                    b.HasIndex("HeadOfDepartmentID");

                    b.HasIndex("ManagingDepartmentDepartmentID");

                    b.HasIndex("ManagingDepartmentID");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("UniversityProject.Domain.Entities.InstructorCourse", b =>
                {
                    b.Property<int>("InstructorID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("CourseID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("InstructorID", "CourseID");

                    b.HasIndex("CourseID");

                    b.ToTable("InstructorCourse");
                });

            modelBuilder.Entity("UniversityProject.Domain.Entities.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("StudentID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("UniversityProject.Domain.Entities.StudentCourse", b =>
                {
                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.HasKey("StudentID", "CourseID");

                    b.HasIndex("CourseID");

                    b.ToTable("StudentCourses");
                });

            modelBuilder.Entity("UniversityProject.Domain.Entities.Department", b =>
                {
                    b.HasOne("UniversityProject.Domain.Entities.Instructor", null)
                        .WithMany("HeadDepartments")
                        .HasForeignKey("InstructorID");

                    b.HasOne("UniversityProject.Domain.Entities.Instructor", "Manager")
                        .WithOne()
                        .HasForeignKey("UniversityProject.Domain.Entities.Department", "ManagerID");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("UniversityProject.Domain.Entities.DepartmentCourse", b =>
                {
                    b.HasOne("UniversityProject.Domain.Entities.Course", "Course")
                        .WithMany("DepartmetsSubjects")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityProject.Domain.Entities.Department", "Department")
                        .WithMany("DepartmentCourses")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UniversityProject.Domain.Entities.Instructor", b =>
                {
                    b.HasOne("UniversityProject.Domain.Entities.Instructor", "HeadOfDepartment")
                        .WithMany()
                        .HasForeignKey("HeadOfDepartmentID");

                    b.HasOne("UniversityProject.Domain.Entities.Department", "ManagingDepartment")
                        .WithMany()
                        .HasForeignKey("ManagingDepartmentDepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityProject.Domain.Entities.Department", "TeachingDepartment")
                        .WithMany("Instructors")
                        .HasForeignKey("ManagingDepartmentID");

                    b.Navigation("HeadOfDepartment");

                    b.Navigation("ManagingDepartment");

                    b.Navigation("TeachingDepartment");
                });

            modelBuilder.Entity("UniversityProject.Domain.Entities.InstructorCourse", b =>
                {
                    b.HasOne("UniversityProject.Domain.Entities.Course", "Course")
                        .WithMany("InstructorCourse")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityProject.Domain.Entities.Instructor", "Instructor")
                        .WithMany("InstructorCourses")
                        .HasForeignKey("InstructorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("UniversityProject.Domain.Entities.Student", b =>
                {
                    b.HasOne("UniversityProject.Domain.Entities.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UniversityProject.Domain.Entities.StudentCourse", b =>
                {
                    b.HasOne("UniversityProject.Domain.Entities.Course", "Course")
                        .WithMany("StudentsCourses")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversityProject.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniversityProject.Domain.Entities.Course", b =>
                {
                    b.Navigation("DepartmetsSubjects");

                    b.Navigation("InstructorCourse");

                    b.Navigation("StudentsCourses");
                });

            modelBuilder.Entity("UniversityProject.Domain.Entities.Department", b =>
                {
                    b.Navigation("DepartmentCourses");

                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("UniversityProject.Domain.Entities.Instructor", b =>
                {
                    b.Navigation("HeadDepartments");

                    b.Navigation("InstructorCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
